// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quest.Infrastructure.Data.EntityFramework;

#nullable disable

namespace Quest.Infrastructure.Migrations
{
    [DbContext(typeof(QuestDbContext))]
    partial class QuestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Quest.Infrastructure.Data.PlayerQuestState", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastMilestoneIndexCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestPointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotalQuestPercentCompleted")
                        .HasColumnType("REAL");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerQuestState");
                });
#pragma warning restore 612, 618
        }
    }
}
